### PR TITLE
Remove EventWithPlatformEvent from libevent and adapt to that patch.

### PR DESCRIPTION
**Pull request by msisov**
This pr removes EventWithPlatformEvent hack and makes appropriate adaptations. Further comments can be read from the actual commit messages.

### CODE REVIEW

**Review by tonikitoo — COMMENTED** [review]
lgtm.

maybe add [DoNoCarryForward] for the sake of git history.

**Review by tonikitoo — COMMENTED** [review]
ideally, we could have git revert the patch being reverted, and cherry pick the one being upstreamed, then a set of fixups. but it is ok.

**Review by tonikitoo — APPROVED** [review]
lgtm

**Comment by msisov** [comment]
Ok, [DoNoCarryForward]  is added

**Pull request merged**
