### PR TITLE
Second attempt to reduce Gpu service start up failure.

### PR DESCRIPTION
**Pull request by tonikitoo**
PR reverts PR #242 and PR #129 (partially).

### CODE REVIEW

**Comment by msisov** [comment]
Should I review it or isn't it ready for review?

**Comment by tonikitoo** [comment]
not yet. I am investigating a possible mojo connection loss or break in the GpuHost vs GpuServiceImpl channel, which might be the actual root cause.

**Review by msisov — APPROVED** [review]
I thought you'll add something else here :)

**Comment by tonikitoo** [comment]
I believe this is a good step forward, per si now. We essentially remove a Sync Wait that we added ourselves, and keep the previous one (already present in upstream).

Work is continuing in getting us free of any sync call, but this should be better than the previous solution.

**Comment by msisov** [comment]
Lgtm, btw

**Pull request closed without merging**
