### PR TITLE
Added implementation for GetRestoredBounds with Desktop/Aura/Ozone

### PR DESCRIPTION
**Pull request by jkim-julie**
This patch made DesktopWindowTreeHostPlatform::GetRestoredBounds
return GetBoundsInPixels because it has platform window's bounds
and platform window has updated bounds.

Issue #448

### CODE REVIEW

**Comment by jkim-julie** [comment]
Hi @msisov, 
This patch added implementation for DesktopWindowTreeHostPlatform::GetRestoredBounds
to keep bounds. Unlike the case of DesktopWindowTreeHostMus, desktop aura doesn't call GetWindowPlacement() directly.

In case of using mus,
NativeBrowserFrameFactory::Create() creates BrowserFrameMus.
When windowTreeHost::OnHostResizedInPixels() is called,
sequences is like DesktopNativeWidgetAura::OnHostResized(),
Widget::OnNativeWidgetSizeChanged(), BrowserFrameMus::GetWindowPlacement()
and DesktopWindowTreeHostMus::GetWindowPlacement().

In case of not using mus,
NativeBrowserFrameFactory::Create() creates DesktopBrowserFrameAura.
When windowTreeHost::OnHostResizedInPixels() is called,
sequences is like DesktopNativeWidgetAura::OnHostResized(),
Widget::OnNativeWidgetSizeChanged() and DesktopBrowserFrameAura::GetWindowPlacement(),
DesktopNativeWidgetAura::GetRestoredBounds(), DesktopNativeWidgetAura::GetRestoredBounds()
and DesktopWindowTreeHostPlatform::GetRestoredBounds().

That's why this change added implementation at DesktopWindowTreeHostPlatform::GetRestoredBounds() to keep bounds.
PTAL.

**Comment by msisov** [comment]
Looks correct. Does it also restores window states? Like maximized, normal and etc on launch?

I see it's done here - https://cs.chromium.org/chromium/src/chrome/browser/ui/views/frame/desktop_browser_frame_aura.cc?type=cs&q=+DesktopBrowserFrameAura::GetWindowPlacement&sq=package:chromium&g=0&l=97, but  just asking to make sure it is so.

**Comment by msisov** [comment]
I think you can already upstream this patch.

**Comment by jkim-julie** [comment]
Yes. I'v done with verifying with minimized, maximized, full-sized and manually resized. All cases works fine. Now I'm preparing upstream.

**Comment by msisov** [comment]
Then it's wrong. Chromium does never restore to the fullscreen mode after reopening a window again.

**Comment by jkim-julie** [comment]
I mean
1) set specific size window->maximized: When it returns back from maximized, it goes to previous size.
2) set specific size window->minimized: When it returns back from minimized, it goes to previous size.
3) set specific size window->fullscreen: When it returns back from fullscreen, it goes to previous size.
4) set specific size window->close and relaunch it: It goes to previous size.

I tested additionally,
1) set maximized, close and relaunch it: it's maximized.
2) set minimized, close and relaunch it: it's not minimized. It shows window on screen, not iconified.
3) set fullscreen, close and relaunch it: it's not fullscreen. it shows window on screen with previous size.

Could you let me know if there is anything I have to check more or among the tests above, is there any other expectation? PTAL.

**Comment by msisov** [comment]
The first part of setting and resetting states is not relevant to this patch and those are ok.

The second part of your tests look ok now. LGTM

Basically, checking how stock chromium behaves is a good example.

**Review by msisov — APPROVED** [review]

**Pull request merged**
